---
title: "Day 10 Comp"
author: "Clarissa Boyajian"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(ggbeeswarm)
library(lubridate)
```

```{r}
ice_cover_data <- read.csv(here("data", "ntl33_v7.csv"), na = c("-999", ""))

meteorological_data <- read_csv(here("data", "ntl20_v6.csv"), na = "-999")
```


```{r}
ggplot(data = ice_cover_data, aes(x = ice_duration, y = lakeid)) +
  geom_jitter(aes(color = lakeid), na.rm = TRUE, show.legend = FALSE) +
  scale_color_manual(values = c("cyan4", "navy", "goldenrod")) +
   geom_violin(na.rm = TRUE, fill = NA) + 
  labs(title = "Total Annual Days with Lake Ice for Lakes in the Madison Area",
       x = "Total Days Annual with Ice",
       y = "Lake Names") +
  scale_y_discrete(labels = c("Lake Mendota", "Lake Monona", "Lake Wingra")) +
  theme(panel.background = element_rect(color = "black"),
        
          )
```

```{r}
ice_cover_mean <- ice_cover_data %>% 
  group_by(year4) %>% 
  summarize(mean_ice_duration = mean(ice_duration))

ggplot(data = ice_cover_mean, aes(x = year4, y = mean_ice_duration)) +
  geom_point() +
  labs(title = "Mean of Madison Area Lake Total Annual Ice Coverage\nper Year 1851  2019",
       y = "Mean Annual Ice Coverage (days)",
       x = "Year") +
  stat_smooth()
  

```
The above graph shows a general downward trend, with the total annual days with ice coverage lessening from 1851 to 2019. 


```{r}
meteorological_mean <- meteorological_data %>% 
  filter(month == c(12, 1, 2)) %>% 
  group_by(year4) %>% 
  summarize(mean_air_temp = mean(ave_air_temp_adjusted))

ggplot(data = meteorological_mean, aes(x = year4, y = mean_air_temp)) +
  geom_point() +
  stat_smooth() +
  labs(title = "Mean Air Temperature of Madison Area Lakes from 1851 to 2019",
       x = "Year", 
       y = "Mean Air Temperature\n(degrees Celsius)")
```

The average air temperature during the winter months near Madison area lakes has a general upward trend from 1851 to 2019. 

```{r}
ice_cover_meteo_means <- meteorological_mean %>% 
  full_join(ice_cover_mean, na.rm = TRUE)

ggplot(data = ice_cover_meteo_means, aes(x = mean_ice_duration, y = mean_air_temp)) +
  geom_point() +
  labs(title = "Mean Winter Ice Temperature Compared to Mean Ice Duration\n1851 to 2019",
       x = "Mean Ice Duration (days)",
       y = "Mean Winter Air Temperature (degrees Celsius)") +
  theme_minimal()
```

This scatter plot shows a slight decrease in total ice duration in days as the average winter air temperature rises.


```{r}
ice_cover_subset <- ice_cover_data %>% 
  filter(year4 >= 1970) %>% 
  mutate(ice_off = as.Date(ice_off)) %>% 
  mutate(ice_off_year = lubridate::yday(ice_off))


ggplot(data = ice_cover_subset, aes(x = ice_off_year, y = year4)) +
  geom_point(aes(color = lakeid))
```






